export const userConstants = {
    SIGNIN: "SIGNIN",
    SIGNUP: "SIGNUP",
    GETALLCAMPAIGNS : "GETALLCAMPAIGNS",
    GETCAMPAIGNBYID : "GETCAMPAIGNBYID",
    GETMYCAMPAIGNS : "GETMYCAMPAIGNS",
    GETMYFUNDINGS : "GETMYFUNDINGS",
}